[package]
name = "denispionicul/countdown"
version = "1.1.0"
registry = "https://github.com/UpliftGames/wally-index"
description = "A modified version of rbxutil's timer module so that it includes a built in countdown"
realm = "shared"

[dependencies]
Timer = "sleitnick/timer@1.1.2"
Signal = "sleitnick/signal@2.0.1"
Trove = "sleitnick/trove@1.3.0"
Promise = "evaera/promise@4.0.0"