[package]
name = "denispionicul/stater"
version = "1.0.3"
registry = "https://github.com/UpliftGames/wally-index"
description = "A simple finite state machine."
realm = "shared"

[dependencies]
Trove = "sleitnick/trove@1.1.0"
Signal = "sleitnick/signal@2.0.1"